version: '3'

services:
  postgres:
    image: postgres:10
    restart: on-failure
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
